// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5B58uwrA9dwIYmMfSm98Ym-zoIxJuCvs',
    appId: '1:613531960974:android:b270598fd3183464c4ebdf',
    messagingSenderId: '613531960974',
    projectId: 'rihlah-75a1b',
    databaseURL: 'https://rihlah-75a1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rihlah-75a1b.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCHANgRhK6dXhcz4otA0YRYxK18toRLw',
    appId: '1:613531960974:web:f32c6bcfc5f7d52ec4ebdf',
    messagingSenderId: '613531960974',
    projectId: 'rihlah-75a1b',
    authDomain: 'rihlah-75a1b.firebaseapp.com',
    databaseURL: 'https://rihlah-75a1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rihlah-75a1b.firebasestorage.app',
    measurementId: 'G-L9JPZDGZYM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5B58uwrA9dwIYmMfSm98Ym-zoIxJuCvs',
    appId: '1:613531960974:ios:placeholder',
    messagingSenderId: '613531960974',
    projectId: 'rihlah-75a1b',
    databaseURL: 'https://rihlah-75a1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rihlah-75a1b.firebasestorage.app',
    iosBundleId: 'com.example.rihlah',
  );

  static const FirebaseOptions macos = ios;
  static const FirebaseOptions windows = ios;
  static const FirebaseOptions linux = ios;
}
